using System;
using System.Collections.Generic;
using System.Text;

namespace Assets.Scripts.Enums
{
    public enum BuildingsTypeEnum
    {
        [OSMtoSharp.Enums.Helpers.Enum("")]
        None,
        [OSMtoSharp.Enums.Helpers.Enum("apartments")]
        Apartments,
        [OSMtoSharp.Enums.Helpers.Enum("farm")]
        Farm,
        [OSMtoSharp.Enums.Helpers.Enum("hotel")]
        Hotel,
        [OSMtoSharp.Enums.Helpers.Enum("house")]
        House,
        [OSMtoSharp.Enums.Helpers.Enum("detached")]
        Detached,
        [OSMtoSharp.Enums.Helpers.Enum("residential")]
        Residential,
        [OSMtoSharp.Enums.Helpers.Enum("dormitory")]
        Dormitory,
        [OSMtoSharp.Enums.Helpers.Enum("terrace")]
        Terrace,
        [OSMtoSharp.Enums.Helpers.Enum("houseboat")]
        Houseboat,
        [OSMtoSharp.Enums.Helpers.Enum("bungalow")]
        Bungalow,
        [OSMtoSharp.Enums.Helpers.Enum("static_caravan")]
        Static_caravan,
        [OSMtoSharp.Enums.Helpers.Enum("commercial")]
        Commercial,
        [OSMtoSharp.Enums.Helpers.Enum("office")]
        Office,
        [OSMtoSharp.Enums.Helpers.Enum("industrial")]
        Industrial,
        [OSMtoSharp.Enums.Helpers.Enum("retail")]
        Retail,
        [OSMtoSharp.Enums.Helpers.Enum("warehouse")]
        Warehouse,
        [OSMtoSharp.Enums.Helpers.Enum("bakehouse")]
        Bakehouse,
        [OSMtoSharp.Enums.Helpers.Enum("cathedral")]
        Cathedral,
        [OSMtoSharp.Enums.Helpers.Enum("chapel")]
        Chapel,
        [OSMtoSharp.Enums.Helpers.Enum("church")]
        Church,
        [OSMtoSharp.Enums.Helpers.Enum("mosque")]
        Mosque,
        [OSMtoSharp.Enums.Helpers.Enum("temple")]
        Temple,
        [OSMtoSharp.Enums.Helpers.Enum("synagogue")]
        Synagogue,
        [OSMtoSharp.Enums.Helpers.Enum("shrine")]
        Shrine,
        [OSMtoSharp.Enums.Helpers.Enum("civic")]
        Civic,
        [OSMtoSharp.Enums.Helpers.Enum("hospital")]
        Hospital,
        [OSMtoSharp.Enums.Helpers.Enum("school")]
        School,
        [OSMtoSharp.Enums.Helpers.Enum("stadium")]
        Stadium,
        [OSMtoSharp.Enums.Helpers.Enum("train_station")]
        Train_station,
        [OSMtoSharp.Enums.Helpers.Enum("transportation")]
        Transportation,
        [OSMtoSharp.Enums.Helpers.Enum("university")]
        University,
        [OSMtoSharp.Enums.Helpers.Enum("public")]
        Public,
        [OSMtoSharp.Enums.Helpers.Enum("barn")]
        Barn,
        [OSMtoSharp.Enums.Helpers.Enum("bridge")]
        Bridge,
        [OSMtoSharp.Enums.Helpers.Enum("bunker")]
        Bunker,
        [OSMtoSharp.Enums.Helpers.Enum("cabin")]
        Cabin,
        [OSMtoSharp.Enums.Helpers.Enum("construction")]
        Construction,
        [OSMtoSharp.Enums.Helpers.Enum("cowshed")]
        Cowshed,
        [OSMtoSharp.Enums.Helpers.Enum("digester")]
        Digester,
        [OSMtoSharp.Enums.Helpers.Enum("farm_auxiliary")]
        Farm_auxiliary,
        [OSMtoSharp.Enums.Helpers.Enum("garage")]
        Garage,
        [OSMtoSharp.Enums.Helpers.Enum("garages")]
        Garages,
        [OSMtoSharp.Enums.Helpers.Enum("greenhouse")]
        Greenhouse,
        [OSMtoSharp.Enums.Helpers.Enum("hangar")]
        Hangar,
        [OSMtoSharp.Enums.Helpers.Enum("hut")]
        Hut,
        [OSMtoSharp.Enums.Helpers.Enum("roof")]
        Roof,
        [OSMtoSharp.Enums.Helpers.Enum("shed")]
        Shed,
        [OSMtoSharp.Enums.Helpers.Enum("stable")]
        Stable,
        [OSMtoSharp.Enums.Helpers.Enum("sty")]
        Sty,
        [OSMtoSharp.Enums.Helpers.Enum("transformer_tower")]
        Transformer_tower,
        [OSMtoSharp.Enums.Helpers.Enum("service")]
        Service,
        [OSMtoSharp.Enums.Helpers.Enum("kiosk")]
        Kiosk,
        [OSMtoSharp.Enums.Helpers.Enum("carport")]
        Carport,
        [OSMtoSharp.Enums.Helpers.Enum("ruins")]
        Ruins,
        [OSMtoSharp.Enums.Helpers.Enum("yes")]
        Yes,
        [OSMtoSharp.Enums.Helpers.Enum("user defined")]
        User_defined

    }
}
