using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Assets.Scripts.Enums
{
    public enum LanduseTypeEnum
    {
        [OSMtoSharp.Enums.Helpers.Enum("")]
        None,
        [OSMtoSharp.Enums.Helpers.Enum("allotments")]
        Allotments,
        [OSMtoSharp.Enums.Helpers.Enum("basin")]
        Basin,
        [OSMtoSharp.Enums.Helpers.Enum("brownfield")]
        Brownfield,
        [OSMtoSharp.Enums.Helpers.Enum("cemetery")]
        Cemetery,
        [OSMtoSharp.Enums.Helpers.Enum("commercial")]
        Commercial,
        [OSMtoSharp.Enums.Helpers.Enum("conservation")]
        Conservation,
        [OSMtoSharp.Enums.Helpers.Enum("construction")]
        Construction,
        [OSMtoSharp.Enums.Helpers.Enum("depot")]
        Depot,
        [OSMtoSharp.Enums.Helpers.Enum("farmland")]
        Farmland,
        [OSMtoSharp.Enums.Helpers.Enum("farmyard")]
        Farmyard,
        [OSMtoSharp.Enums.Helpers.Enum("forest")]
        Forest,
        [OSMtoSharp.Enums.Helpers.Enum("garages")]
        Garages,
        [OSMtoSharp.Enums.Helpers.Enum("grass")]
        Grass,
        [OSMtoSharp.Enums.Helpers.Enum("greenfield")]
        Greenfield,
        [OSMtoSharp.Enums.Helpers.Enum("greenhouse_horticulture")]
        GreenhouseHorticulture,
        [OSMtoSharp.Enums.Helpers.Enum("industrial")]
        Industrial,
        [OSMtoSharp.Enums.Helpers.Enum("landfill")]
        Landfill,
        [OSMtoSharp.Enums.Helpers.Enum("meadow")]
        Meadow,
        [OSMtoSharp.Enums.Helpers.Enum("military")]
        Military,
        [OSMtoSharp.Enums.Helpers.Enum("orchard")]
        Orchard,
        [OSMtoSharp.Enums.Helpers.Enum("pasture")]
        Pasture,
        [OSMtoSharp.Enums.Helpers.Enum("peat_cutting")]
        PeatCutting,
        [OSMtoSharp.Enums.Helpers.Enum("plant_nursery")]
        PlantNursery,
        [OSMtoSharp.Enums.Helpers.Enum("port")]
        Port,
        [OSMtoSharp.Enums.Helpers.Enum("quarry")]
        Quarry,
        [OSMtoSharp.Enums.Helpers.Enum("railway")]
        Railway,
        [OSMtoSharp.Enums.Helpers.Enum("recreation_ground")]
        RecreationGround,
        [OSMtoSharp.Enums.Helpers.Enum("reservoir")]
        Reservoir,
        [OSMtoSharp.Enums.Helpers.Enum("residential")]
        Residential,
        [OSMtoSharp.Enums.Helpers.Enum("retail")]
        Retail,
        [OSMtoSharp.Enums.Helpers.Enum("salt_pond")]
        SaltPond,
        [OSMtoSharp.Enums.Helpers.Enum("village_green")]
        VillageGreen,
        [OSMtoSharp.Enums.Helpers.Enum("vineyard")]
        Vineyard
    }
}
